### ISSUE TITLE
Проблемы с решением poisson

### ISSUE THREAD

**Issue by damirkamur** [kalininei/CFDCourse22#10]
В общем ситуация такая. Решатели Jacoby и Seidel написаны. Тесты и там и там проходят, но при этом решение poisson идет куда-то не туда (сходится к другим значениям), при этом к одинаковым. В чем может быть проблема?

_По сути для решения мы раскомментировали строку poisson.cpp:25_

**Comment by kalininei** [comment]
Откудаж мне знать)
Если вы получаете ответ, который не удовлетворяет исходной СЛАУ, то у вас решатель сходится не должен.
А если удовлетворяет, значит матрица неправильно собрана.
Отлаживайтесь.

**Comment by kalininei** [comment]
НАчните с простой одномерной задачи с тремя узлами. Потом усложняйте.

**Comment by Maria-Muhina** [comment]
Доброго времени суток!

Стали решать на простых сетках -- действительно, там проблем нет.

Для сетки типа GridBuilder::build_regular1(1, 2) для того, чтобы решение сошлось достаточно 10 итераций.
Если увеличиваем сетку, например, GridBuilder::build_regular1(1, 5) -- при том же требовании по погрешности сходится при 50 итерациях. Если повышаем точность, все так же сходится (даже при том же количестве итераций).
Увеличиваем еще, пусть даже GridBuilder::build_regular1(1, 6) -- увеличение числа итераций уже ничего не дает -- сходимость есть, но не вокруг решения и все ломается...

Как тут рассуждать? Такое ощущение, что просто сами методы (Якоби и Зейделя) эффективны лишь до определенных границ.

**Comment by Maria-Muhina** [comment]
Доброго времени суток! 

Стали решать на простых сетках -- действительно, там проблем нет.

Для сетки типа GridBuilder::build_regular1(1, 2) для того, чтобы решение сошлось достаточно 10 итераций.
Если увеличиваем сетку, например, GridBuilder::build_regular1(1, 5) -- при том же требовании по погрешности сходится при 50 итерациях. Если повышаем точность, все так же сходится (даже при том же количестве итераций).
Увеличиваем еще, пусть даже GridBuilder::build_regular1(1, 6) -- увеличение числа итераций уже ничего не дает -- сходимость есть, но не вокруг решения и все ломается...

Как тут рассуждать? Такое ощущение, что просто сами методы (Якоби и Зейделя) эффективны лишь до определенных границ.

**Comment by kalininei** [comment]
Не знаю, сейчас написал. Метод Якоби сошёлся на дефолтных установках за 28К итераций. Ищите ошибки

В программе linear_fvm1() c 101 узлом

**Comment by kalininei** [comment]
> Для сетки типа GridBuilder::build_regular1(1, 2) для того, чтобы решение сошлось достаточно 10 итераций.

Если у вас два узла, то сойтись должно вообще сразу. Там же задача первого рода и решать нечего.

**Comment by kalininei** [comment]
Хотя, да, там же метод конечных объёмов и одна неизвестная всё же есть для 2х узлов. Тем не менее у меня за 3 итерации сходится в этом случае до точного решения.

Решите эту матрицу руками и от этого отлаживайтесь.

**Comment by Maria-Muhina** [comment]
Для двух узлов за 3 итерации до точного у нас тоже сходится.
Проблемы на больших сетках

**Comment by kalininei** [comment]
Вы до этого написали, что за 10.
Значит решайте руками задачу для 6 узлов. Хотя бы первые несколько итераций и сравнивайте.
