### ISSUE TITLE
Генерация сеток в fvm2

### ISSUE THREAD

**Issue by victorpichugov** [kalininei/CFDCourse22#2]
Добрый день, Евгений Игоревич! Сейчас по лекциям остановился на 3, появились вопросы. 
Я начал разбираться с файлом fvm2.m , чтобы он работал нужно : 
1) исправить ту ошибку, о которой Вы писали ранее в tasks;
2) разобраться, как работает утилита grid2utils

В утилите grid2utils есть функции, которые зависят от входного файла fn, который был экспортирован из gmsh. Далее в папке instructions нахожу gmsh-tutorial, который поможет сгенерировать сетку.

Вопросы:
1) Зачем мы в утилите grid2utils применяем функцию gu_save _vtk _elemdata для экспорта сетки в формат vtk?
2) Я правильно понял, что весь алгоритм мы начинаем с генератора сеток Gmsh, далее сетку экспортируем в формат .m. 
После этого  grid2utils может прочитать сетку , утилита работает. Утилита работает, значит fvm2 работает?

**Comment by kalininei** [comment]
Исправлять ошибку не нужно, я её уже исправил. Сейчас там рабочий код

1 Мы утилиту gu_save_vtk_elemdata не применяем в grid2utils, а реализуем её там. Применяем её мы в расчётых программах. Например, в fvm2. Для того, чтобы сохранить решение и посмотреть его в paraview. 

2. Да. Создаём сетку в gmsh и грузим её через gu_build_from_gmsh_m. Если это сработало, значит сетка прочиталась. О работоспособности fvm2 это не говорит.

**Comment by victorpichugov** [comment]
Спасибо, стало понятнее.
