### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by damirkamur** [kalininei/CFDCourse22#3]
**Здравствуйте, Евгений Игоревич.**
Есть вопрос по поводу заданий лекции №5.
В задаче переноса используются модуль femutils.m, а в нем куча других - ("Unknown","D1Lin", "D1Sqr","D1Hermite", ...)
Конкретно здесь, как мы поняли, используется только D1Lin.m

```
function ret = D1Lin(vertices, ibasis)                                              //Функция возвращает экземпляр класса D1Lin
		assert(size(ibasis) == [1, 2]);                                     // Проверка на корректность входных данных
		assert(size(vertices) == [2, 1]);                                   ↑

		L = vertices(2) - vertices(1);                                      //Длина элемента

		ret.ibasis = ibasis;                                            ?// Базисом являются индексы элементов
		ret._h = L;
		ret.mass = L * [1/3, 1/6; 1/6, 1/3];                             ↓ 
		ret.stiff = 1.0/L * [ 1, -1; -1,  1];                            →  ? // Матрица масс и Stiffness - понятно, а что за lumped_mass
		ret.lumped_mass = L*[1/2; 1/2];                                  ↑
		ret.tran = {[-1/2, 1/2; -1/2, 1/2]};                        ?// Тоже непонятно что это

		ret._p0 = vertices(1);                                     ?// И вот это
	endfunction
```

**Comment by damirkamur** [comment]
И еще вопрос: что делает функция fem_elements_report?
Она же носит чисто информативный характер ?

**Comment by kalininei** [comment]
Вы опять не с того конца программу смотрите.
Надо начинать смотреть сверху, с функций высокого уровня. Там сразу видно, какие поля класса для чего используются и что они значат. А если не используются, значит они и не нужны (для конкретной задачи).

Конкретно этот класс - это одномерный линейный элемент. Все его публичные поля описаны в секции properties.

ibasis - это глобальные индексы локльных базисов
lumped_mass - это диагональная матрица масс = integral(phi_i)
tran - матрицы переноса integral(dphi_i / dx)

всё, что с подчёркиванием - это приватные поля, используемые для внутренних процедур. 


функция fem_elements_report - ничего не делает, просто печатает количество и вид используемых элементов.

**Comment by damirkamur** [comment]
А какие сетки по количеству элементов должны быть корректными для этой задачи?
t = 0.1 N = 30
![image](https://user-images.githubusercontent.com/84187078/166450272-741a3082-b193-4fb9-986f-cbf13fa87ada.png)
t = 0.1 N = 1000
![image](https://user-images.githubusercontent.com/84187078/166450408-13a7e090-0562-45b9-94f4-938d312fee61.png)

Как понять, что решение идет правильно и нет ошибок в уравнениях? 
У нас с ростом разбиения погрешность уменьшается, но сетка в 1000 узлов не слишком ли большая для 1D задачи?

**Comment by kalininei** [comment]
По поведению нормы. Если порядок аппроксимации выдерживается, то всё нормально (скорее всего).

Здесь у вас разрыв какой-то. Не помню, чтобы я давал такие задачи.

**Comment by damirkamur** [comment]
О каком разрыве идет речь? 
Это задача переноса с периодическими условиями в некоторый промежуточный момент времени (t = 0.1)

**Comment by kalininei** [comment]
А, все вижу.
Я там имел ввиду, конечно, не делить, а умножить.
u(x + nT) = exp(-(x*10)^2);

Нужно решение в виде бегущей волны, изменяющееся от 0 до 1.

**Comment by damirkamur** [comment]
И, вероятно, последний вопрос:
вот так находится матрица масс
![image](https://user-images.githubusercontent.com/84187078/166455519-681eecfc-27b4-46be-858c-cbee9da00609.png)
А как находить S (тут обозначена как T)?
Ясно что надо использовать вот эту формулу:
![image](https://user-images.githubusercontent.com/84187078/166455688-4fa07661-d242-4aed-9cd2-6f21abb6fec2.png)
(Из нее и получается 1/L),
Но что делать с этим?:
![image](https://user-images.githubusercontent.com/84187078/166455889-b862fa28-631a-44a3-bca0-a8eb118b01f9.png)

**Comment by damirkamur** [comment]
Хотя вопрос скорее в том почему остается 1/L:
![image](https://user-images.githubusercontent.com/84187078/166456557-1becf478-3dec-4db9-810a-76aa9bfe90ed.png)

**Comment by kalininei** [comment]
А с чего вы взяли, что она там остается? Это матрица переноса. У меня она вычислена безо всяких L:
ret.tran = {[-1/2, 1/2; -1/2, 1/2]};

**Comment by damirkamur** [comment]
Да, мой косяк - не туда посмотрел, но в любом случае, разве не должны T12 и T21 быть поменяны местами?
![image](https://user-images.githubusercontent.com/84187078/166457916-3a60179b-b8a6-4f19-991f-ffdff2779bed.png)

**Comment by damirkamur** [comment]
Так получается неверный ответ (а с Вашим вариантом - правильный). Но не понимаю почему так

**Comment by kalininei** [comment]
А почему у вас порядок `(dphi_i) * phi_j` под интегралом?
У меня в коде индекс i - это индекс весовой функции (номер уравнения), а индекс j -- это индекс суммирования при разложении функции по базису. Поэтому наоборот должно быть `dphi_j/dx * phi_i`

**Comment by damirkamur** [comment]
Наконец понял) Спасибо большое за разъяснения

**Comment by Maria-Muhina** [comment]
Добрый день, Евгений Игоревич!
Есть еще вопрос по предыдущим заданиям.
1. Правильно ли мы понимаем, что в последнем выражении идет сумма по i от произведения сконцентрированной матрицы масс и квадрата разности решений?
2. Для МКО i-е значение соответствует значению в центре i-го элемента?
3. Для МКЭ i-е значение соответствует значению в i-ом узле?
![image](https://user-images.githubusercontent.com/100961838/166666381-76a5437e-185a-45f5-b6b7-ac0f6f39f417.png)

**Comment by kalininei** [comment]
1) да, в формуле 2 квадрат пропущен в конце
2) да
3) да

**Comment by damirkamur** [comment]
Добрый день!
Просто ведь все матрицы мы определяем для конкретного элемента, а не для узла. 
M_i^L  для МКЭ тогда будет вычисляться как сумма по нескольким элементам?

**Comment by kalininei** [comment]
Во-первых не для узла, а для базиса.
Просто мы успели рассмотреть только узловые КЭ, где каждому базису соответсвует какой-то узел.

Во-вторых, базис глобальный. Локальные базисы -- это способ сборки глобальных матриц. Ну и для удобства работы внутри элемента.
`M^L` -- это именно глобальная диагональная матрица, которая собирается из локальных также, как и другие глобальные матрицы.

**Comment by damirkamur** [comment]
Еще раз добрый вечер!

Это снова мы)
вопрос по последнему заданию (пункт 2):
![image](https://user-images.githubusercontent.com/84187078/166712737-84667ccb-a45c-4077-b938-0aa2be5d0599.png)
Как и где построить такую сетку? На сетке из условных 10 элементов можно вручную удалить фейсы между треугольниками и получить четырехугольники (gmsh)
Но для более крупных сеток это уже не вариант

**Comment by kalininei** [comment]
В gmsh есть функция построения 4-x угольной сетки из треугольной. Recombine кажется называется.
Эта функция везде, где может объединяет треугольники в 4x угольники. Может даже все объединить и вообще треугольников не остаться.

Если такое случится, можете искусственно разбить пару 4x угольников. Просто чтобы продемонстрировать, что ваша программа может работать с такими сетками.

**Comment by damirkamur** [comment]
ну вот да - recombine делает из треугольников четырехугольники, но в нашем случае идеально заменяет их все. Так что тогда просто вручную добавим четырехугольников на треугольную сетку

**Comment by kalininei** [comment]
А нельзя наоборот: добавить треугольники в 4угольную? По-моему это проще. Да и решение точнее на билинейном базисе.
Впрочем, смотрите сами.
