### ISSUE TITLE
Установка amgcl и boost

### ISSUE THREAD

**Issue by damirkamur** [kalininei/CFDCourse22#7]
Доброе время суток. По некоторым причинам переустанавливал систему и в итоге установку пакетов AMGCL и Boost нужно делать заново.
Как это правильно нужно сделать (на Ubuntu). Если Boost еще можно установить через apt-get, То amgcl это просто репозиторий. Куда его нужно клонировать или нужно что-то другое?

Сейчас вот такая ошибка

**Comment by damirkamur** [comment]
![image](https://user-images.githubusercontent.com/84187078/210837215-b3a10ad5-391f-4e56-b880-6e615390735b.png)

**Comment by kalininei** [comment]
Нужно взять папку amgcl из репозитория https://github.com/ddemidov/amgcl и пололжить её в системные пути.
В /usr/local/include, если такая есть в убунте. Или просто в /usr/include
