### ISSUE TITLE
Создание матрицы CSR при входных CsrStencil и mat_values

### ISSUE THREAD

**Issue by damirkamur** [kalininei/CFDCourse22#8]
Нужно при вызове функции `set_matrix` записать в приватные аргументы решателя матрицу.
![image](https://user-images.githubusercontent.com/84187078/211150064-31080a73-f794-4ed4-999e-e80fbe03d391.png)

У CsrStencil есть метод build, но он тут явно не при чем. У CSRMatrix же нет даже конструктора. Каким образом это надо делать? Что бы в дальнейшем нормально работать с матрицей?

**Comment by damirkamur** [comment]
`this->matrix = ....???`

**Comment by kalininei** [comment]
Если вам чего-то не хватает в методах CsrMatrix, добавьте.
Или используйте вместо CsrMatrix данные в виде CsrStencil + vector<double>

**Comment by damirkamur** [comment]
т.е. на данном этапе создание экземпляра CSRMatrix не предусмотрено?

**Comment by damirkamur** [comment]
здесь скорее вопрос тестирования. 
Нудно будет вызвать функцию set_matrix И потом solve.
Вот вопрос, что туда конкретно передавать и как.
Можно ли какой-нибудь конкретный пример?

**Comment by kalininei** [comment]
Конкретный пример чего вам нужен? Сигнатуры вызвова решателя уже прописаны. У вас в классе JacobiSolver в публичной секции в том числе. Остаётся только реализовать. Как реализовать, смотрите сами. Весь код ваш. Если вам не хватает какого-то метода в CSRMatrix - допишите его.

В чём вопрос тестирования -- я тоже не понимаю.  Если тестируете чисто решатель, то да
1) собираете матрицу и правую часть
2) set_matrix
3) solve
4) CHECK

А для отчёта нужно решить задачу из poisson.cpp вашим решателем.
