### ISSUE TITLE
Проблема в создании Stensil

### ISSUE THREAD

**Issue by damirkamur** [kalininei/CFDCourse22#9]
Старался сделать по аналогии с той функцией которая уже есть, но что-то не идет. Как правильно ?
Цель в том что бы создавать Stensil по привычным для CSR формата данным
![image](https://user-images.githubusercontent.com/84187078/211208044-8209bd3b-a2e2-44f2-bd9b-84c87ab5b8cf.png)
![image](https://user-images.githubusercontent.com/84187078/211208051-6af80824-be59-4c97-8da4-50e91fb910d0.png)

**Comment by kalininei** [comment]
Move уберите, у вас же тут левая ссылка

**Comment by damirkamur** [comment]
![image](https://user-images.githubusercontent.com/84187078/211208451-c8e35bf7-bb62-4868-b74e-50ba413af832.png)
и вот еще проблема

**Comment by damirkamur** [comment]
![image](https://user-images.githubusercontent.com/84187078/211208473-99c58f51-6681-4ab2-a4f7-a2870869068b.png)
как передавать-то?

**Comment by damirkamur** [comment]
и тут тоже проблема не решается
![image](https://user-images.githubusercontent.com/84187078/211208535-0d4a98a6-7462-4853-aab1-355b8543c4f5.png)

**Comment by damirkamur** [comment]
Проблема в том как в функции эти передавать аргументы, из-за этого  не получается приступить к написанию функции solve, т.к. неясно как с этим вообще работать....

**Comment by kalininei** [comment]
Я не понимаю, зачем вам этот build().
Пустой конструктор + set_data вашу задачу решает. В контексте test_1, во всяком случае. Зачем сущности множить?

Вы не понимаете как set_data что ли вызвать? Нужно правую ссылку создать. 

```cpp
CsrStencil ret;
std::vector<int> addr2(addr);
std::vector<int>cols2(cols);
ret.set_data(std::move(addr2), std::move(cols));
```

**Comment by kalininei** [comment]
Или даже так
```cpp
CsrStencil ret;
ret.set_data(std::vector<int>(addr), std::vector<int>(cols));
```

**Comment by damirkamur** [comment]
а с этим как быть?
![image](https://user-images.githubusercontent.com/84187078/211208940-80adc1d9-2234-4953-b169-a9dfe1f00cc1.png)

**Comment by damirkamur** [comment]
Стоит просто передача по ссылке, но вызов ругается

![image](https://user-images.githubusercontent.com/84187078/211209041-805d71dc-e165-45e1-9b06-af83b84cc3fe.png)

**Comment by kalininei** [comment]
В интерфейсе CsrStencil нет метода build(vector<vector<int>>). Поэтому и ругается

**Comment by damirkamur** [comment]
а как правильно вызвать от множества?

**Comment by damirkamur** [comment]
никогда с ними (разумеется в C++) не работал. Можете пожалуйста пример написать (на примере матрицы выше)?

**Comment by kalininei** [comment]
```cpp
std::vector<std::set<int>> stencil_set{{0}, {0, 1}, {0, 1, 2}}; 
```

**Comment by damirkamur** [comment]
Спасибо

**Comment by damirkamur** [comment]
Но опять что-то ломается...
![image](https://user-images.githubusercontent.com/84187078/211209477-9c39f670-a372-4e3b-b1a3-5679be8fd631.png)

**Comment by kalininei** [comment]
Сборочный скрипт смотрите. Наверно библиотеку cfdlib не прицепили.

**Comment by damirkamur** [comment]
А теперь такой вопрос. Начали писать solver.
в итоге cols сохранились не так как хотелось.
**Правильно ли мы поняли** что ЕСЛИ ЕСТЬ диагональный элемент, то он ижет на первое место, а остальные идукт строго по возрастанию?

**Comment by kalininei** [comment]
Диагональный элемент всегда есть. Если его нет, то явно пишется ноль. На первом месте.

**Comment by damirkamur** [comment]
А чем вызвана вот эта проблема?
![image](https://user-images.githubusercontent.com/84187078/211213598-a3544861-3480-4d70-9da1-75c919925e9c.png)
![image](https://user-images.githubusercontent.com/84187078/211213606-febe9e67-114d-4b65-ac22-5eb0c11b0a23.png)

**Comment by kalininei** [comment]
Наверное тем, что вы вызываете не-const метод из const-метода

**Comment by damirkamur** [comment]
а где этот метод const?

**Comment by damirkamur** [comment]
а все. понял
